#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Daniel Polo
"""Agent-runnable consistency lint for pgs-eadros (generated by EADOS).

A dependency-free (Python 3 standard library only) checker that asserts the project is
internally congruent after any change. Run from anywhere in the repo:

    python tools/consistency_lint.py

It exits non-zero with an actionable report when a congruence invariant is violated. The
contract (the "congruence checks"):

  1. version-lockstep — the version constant, the README `Status-vX.Y.Z` badge, and the
     latest released changelog/release file (if any) agree;
  2. adr-index       — every docs/adr/NNNN-*.md is indexed and every indexed ADR exists,
     with sequential numbering and no gap;
  3. patterns        — every Implemented/Planned catalogue row cites an existing ADR and an
     existing code location under the source tree;
  4. spec-map        — the ROADMAP Spec Coverage Map has no dangling row;
  5. milestones      — README ↔ ROADMAP milestone-completion state is consistent and no
     checkbox is malformed;
  6. bugs            — every docs/bugs/ record has valid frontmatter, its filename/path
     agrees with its id/discovered date, ids are unique and non-gapped, the index ↔ files
     bijection holds, and a `fixed` record names its `fixed-in`;
  7. i18n-freshness  — (only when i18n is enabled) no translated page is staler than its
     English source.

Each check is independent; all run, then the report lists every failure. The checks are
designed to PASS on a freshly-generated repository (empty catalogues, no releases yet).

Generated configuration is in the CONFIG block below — EADOS fills it from project.yaml.
"""

import os
import re
import subprocess
import sys

# ---------------------------------------------------------------------------
# CONFIG — filled by EADOS at generation time from orchestrator/project.yaml.
# ---------------------------------------------------------------------------
CONFIG = {
    # The file holding the version constant, relative to the repo root, or None if the
    # version lives only in a build manifest the lint should not parse. When None (or the
    # file is absent), version-lockstep derives the source version from the README badge.
    "version_file": "src/main/typescript/dev/d4np/eadros/version.ts",
    # A regex with a single (\d+\.\d+\.\d+) group that extracts the version from that file.
    "version_regex": r"(\d+\.\d+\.\d+)",
    # The source root that pattern code-locations must live under.
    "src_main": "src/main/typescript/dev/d4np/eadros",
    # Whether documentation i18n is enabled (gates check 7).
    "i18n_enabled": False,
}

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
failures = []  # list of (check_name, message)


def fail(check, message):
    failures.append((check, message))


def read(*parts):
    with open(os.path.join(ROOT, *parts), encoding="utf-8") as handle:
        return handle.read()


def exists(rel):
    return os.path.exists(os.path.join(ROOT, rel))


def git(*args):
    try:
        out = subprocess.run(
            ["git", "-C", ROOT, *args], capture_output=True, text=True, check=True
        )
        return out.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def semver_tuple(text):
    m = re.search(r"(\d+)\.(\d+)\.(\d+)", text)
    return tuple(int(g) for g in m.groups()) if m else None


# ---------------------------------------------------------------------------
# 1. Version lockstep
# ---------------------------------------------------------------------------
def check_version_lockstep():
    name = "version-lockstep"
    readme = read("README.md")
    bm = re.search(r"Status-v(\d+\.\d+\.\d+)", readme)
    if bm is None:
        fail(name, "no `Status-vX.Y.Z` badge found in README.md")
        return
    badge = bm.group(1)

    # Source of truth: the version file if present, else the badge itself.
    source = badge
    vf = CONFIG.get("version_file")
    if vf and exists(vf):
        text = read(*vf.split("/"))
        vm = re.search(CONFIG["version_regex"], text)
        if vm is None:
            fail(name, f"could not parse a version from {vf} with the configured regex")
            return
        source = vm.group(1)
        if badge != source:
            fail(name, f"README badge v{badge} != version file {vf} ({source})")

    # Latest released changelog file (per-version split), if any exist.
    cl_dir = os.path.join(ROOT, "docs", "changelog")
    cl = []
    if os.path.isdir(cl_dir):
        for cur, _d, files in os.walk(cl_dir):
            for fn in files:
                m = re.fullmatch(r"v(\d+\.\d+\.\d+)\.md", fn)
                if m:
                    cl.append(m.group(1))
    if cl:
        latest = max(cl, key=semver_tuple)
        if latest != source:
            fail(name, f"latest docs/changelog v{latest} != source version {source}")

    # Latest release-notes file, if any exist.
    rel_dir = os.path.join(ROOT, "docs", "releases")
    rel = []
    if os.path.isdir(rel_dir):
        for fn in os.listdir(rel_dir):
            m = re.fullmatch(r"v(\d+\.\d+\.\d+)\.md", fn)
            if m:
                rel.append(m.group(1))
    if rel:
        latest = max(rel, key=semver_tuple)
        if latest != source:
            fail(name, f"latest docs/releases/v{latest}.md != source version {source}")


# ---------------------------------------------------------------------------
# 2. ADR index bijection + sequential numbering
# ---------------------------------------------------------------------------
def check_adr_index():
    name = "adr-index"
    adr_dir = os.path.join(ROOT, "docs", "adr")
    if not os.path.isdir(adr_dir):
        fail(name, "docs/adr/ directory is missing")
        return
    files = sorted(fn for fn in os.listdir(adr_dir) if re.fullmatch(r"\d{4}-.+\.md", fn))
    if not files:
        fail(name, "no ADR files found (expected at least 0001 and 0002)")
        return
    index = read("docs", "adr", "README.md")
    for fn in files:
        if fn[:-3] not in index:
            fail(name, f"ADR '{fn[:-3]}' is not listed in docs/adr/README.md")
    nums = [int(fn[:4]) for fn in files]
    for i, n in enumerate(nums, start=1):
        if n != i:
            fail(name, f"ADR numbering gap/dup: expected {i:04d}, found {n:04d}")
            break
    for num in re.findall(r"\]\((\d{4}-[a-z0-9-]+\.md)\)", index):
        if not os.path.exists(os.path.join(adr_dir, num)):
            fail(name, f"index links missing ADR file '{num}'")


# ---------------------------------------------------------------------------
# 3. Catalogued patterns -> ADR + code location (tolerant of an empty catalogue)
# ---------------------------------------------------------------------------
def check_patterns():
    name = "patterns"
    if not exists("docs/patterns/README.md"):
        fail(name, "docs/patterns/README.md is missing")
        return
    cat = read("docs", "patterns", "README.md")
    # Real Implemented/Planned rows start with `| <digits> |`. The `| — |` placeholder row is
    # ignored, so a freshly-generated empty catalogue passes.
    rows = re.findall(r"^\|\s*\d+\s*\|.*\|.*$", cat, re.MULTILINE)
    catalogued = [r for r in rows if "Implemented" in r or "Planned" in r]
    for row in catalogued:
        pattern = row.split("|")[2].strip()
        adrs = re.findall(r"\((?:\.\./)*adr/(\d{4}-[a-z0-9-]+\.md)\)", row)
        if not adrs:
            fail(name, f"pattern '{pattern}': no ADR link in its row")
        for adr in adrs:
            if not exists(os.path.join("docs", "adr", adr)):
                fail(name, f"pattern '{pattern}': ADR '{adr}' does not exist")
        code = re.findall(r"\((?:\.\./)*(src/[A-Za-z0-9_./-]+)\)", row)
        if not code:
            fail(name, f"pattern '{pattern}': no source code location in its row")
        for path in code:
            if not exists(path):
                fail(name, f"pattern '{pattern}': code location '{path}' does not exist")


# ---------------------------------------------------------------------------
# 4. Spec Coverage Map — no dangling row
# ---------------------------------------------------------------------------
def check_spec_map():
    name = "spec-map"
    roadmap = read("ROADMAP.md")
    block = re.search(r"## Spec Coverage Map.*?(?=\n## |\Z)", roadmap, re.DOTALL)
    if block is None:
        fail(name, "no '## Spec Coverage Map' section in ROADMAP.md")
        return
    glyphs = {"⏳", "🚧", "✅", "❎"}
    seen = 0
    for line in block.group(0).splitlines():
        if not line.startswith("| §"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 4:
            fail(name, f"malformed Spec Coverage Map row: {line.strip()}")
            continue
        seen += 1
        section, items, status = cells[0], cells[2], cells[3]
        if not items:
            fail(name, f"spec row {section} has an empty 'Roadmap items' cell (dangling)")
        if not any(g in status for g in glyphs):
            fail(name, f"spec row {section} has no recognised status glyph: '{status}'")
    if seen == 0:
        fail(name, "Spec Coverage Map has no '| §...' rows")


# ---------------------------------------------------------------------------
# 5. ROADMAP <-> README milestone completion consistency
# ---------------------------------------------------------------------------
def check_milestones():
    name = "milestones"
    readme = read("README.md")
    roadmap = read("ROADMAP.md")
    readme_status = {}
    for m in re.finditer(r"^\|\s*(\d+)\s*\|[^|]+\|\s*([^|]+?)\s*\|$", readme, re.MULTILINE):
        readme_status[int(m.group(1))] = "✅" in m.group(2)
    if not readme_status:
        fail(name, "no milestone table rows parsed from README.md")
        return
    sections = re.split(r"^## Milestone (\d+)", roadmap, flags=re.MULTILINE)
    roadmap_complete = {}
    for i in range(1, len(sections), 2):
        num = int(sections[i])
        body = sections[i + 1].split("\n## ")[0]
        items = re.findall(r"^- \[([ xX])\]\s", body, re.MULTILINE)
        if items:
            roadmap_complete[num] = all(c.lower() == "x" for c in items)
    for num, complete in readme_status.items():
        if complete and num in roadmap_complete and not roadmap_complete[num]:
            fail(name, f"README marks Milestone {num} complete, but ROADMAP has "
                       "unchecked item(s) in that milestone")
    for ln in roadmap.splitlines():
        if re.match(r"^- \[", ln) and not re.match(r"^- \[[ xX]\]\s", ln):
            fail(name, f"malformed ROADMAP checkbox: {ln.strip()[:60]}")


# ---------------------------------------------------------------------------
# 6. Bug ledger integrity
# ---------------------------------------------------------------------------
BUG_STATUSES = {"open", "confirmed", "fixed", "wontfix", "rejected", "duplicate",
                "cannot-reproduce"}   # `rejected`: an unsubstantiated report (ledger README, #242)
BUG_SEVERITIES = {"low", "medium", "high", "critical"}
BUG_REPORTERS = {"internal", "third-party"}
BUG_REQUIRED = ("id", "title", "status", "severity", "reporter", "discovered")


def _parse_frontmatter(text):
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    fields = {}
    for line in text[3:end].splitlines():
        if not line.strip() or ":" not in line:
            continue
        key, _, value = line.partition(":")
        fields[key.strip()] = value.strip()
    return fields


def check_bugs():
    name = "bugs"
    bugs_dir = os.path.join(ROOT, "docs", "bugs")
    if not os.path.isdir(bugs_dir):
        return
    index_path = os.path.join(bugs_dir, "README.md")
    index = read("docs", "bugs", "README.md") if os.path.exists(index_path) else ""
    numbers = []
    for cur, _d, files in os.walk(bugs_dir):
        for fn in files:
            m = re.fullmatch(r"BUG-(\d{4})-[a-z0-9-]+\.md", fn)
            if not m:
                continue
            num = int(m.group(1))
            rel = os.path.relpath(os.path.join(cur, fn), bugs_dir).replace(os.sep, "/")
            fm = _parse_frontmatter(read("docs", "bugs", *rel.split("/")))
            if fm is None:
                fail(name, f"{rel}: missing or malformed YAML frontmatter")
                continue
            for key in BUG_REQUIRED:
                if not fm.get(key):
                    fail(name, f"{rel}: missing required frontmatter key '{key}'")
            if fm.get("id") != f"BUG-{m.group(1)}":
                fail(name, f"{rel}: frontmatter id '{fm.get('id')}' != filename BUG-{m.group(1)}")
            if fm.get("status") and fm["status"] not in BUG_STATUSES:
                fail(name, f"{rel}: unknown status '{fm['status']}'")
            if fm.get("severity") and fm["severity"] not in BUG_SEVERITIES:
                fail(name, f"{rel}: unknown severity '{fm['severity']}'")
            if fm.get("reporter") and fm["reporter"] not in BUG_REPORTERS:
                fail(name, f"{rel}: unknown reporter '{fm['reporter']}'")
            disc = fm.get("discovered", "")
            dm = re.fullmatch(r"(\d{4})-(\d{2})-\d{2}", disc)
            if not dm:
                fail(name, f"{rel}: discovered '{disc}' is not YYYY-MM-DD")
            elif f"{dm.group(1)}/{dm.group(2)}/" not in rel:
                fail(name, f"{rel}: path does not match discovered date {disc}")
            if fm.get("status") == "fixed" and not fm.get("fixed-in"):
                fail(name, f"{rel}: status 'fixed' requires a 'fixed-in' release")
            if f"({rel})" not in index:
                fail(name, f"{rel} is not linked from docs/bugs/README.md index")
            numbers.append(num)
    if numbers:
        if len(set(numbers)) != len(numbers):
            fail(name, "duplicate BUG ids found")
        for i, n in enumerate(sorted(numbers), start=1):
            if n != i:
                fail(name, f"BUG numbering gap/dup: expected {i:04d}, found {n:04d}")
                break
    for link in re.findall(r"\]\((\d{4}/\d{2}/BUG-\d{4}-[a-z0-9-]+\.md)\)", index):
        if not os.path.exists(os.path.join(bugs_dir, link)):
            fail(name, f"index links missing bug file '{link}'")


# ---------------------------------------------------------------------------
# 7. i18n freshness (only when enabled)
# ---------------------------------------------------------------------------
def check_i18n_freshness():
    name = "i18n-freshness"
    if not CONFIG.get("i18n_enabled"):
        return
    manifest_rel = os.path.join("docs", "i18n", "translation-status.md")
    if not exists(manifest_rel):
        fail(name, f"i18n enabled but {manifest_rel} is missing")
        return
    manifest = read("docs", "i18n", "translation-status.md")
    i18n_dir = os.path.join(ROOT, "docs", "i18n")
    for line in manifest.splitlines():
        if not line.lstrip().startswith("| ["):
            continue
        if "`translated`" not in line:
            continue
        link = re.search(r"\]\(([^)]+)\)", line)
        sha = re.search(r"\|\s*`([0-9a-f]{7,40})`\s*\|", line)
        if link is None or sha is None:
            fail(name, f"could not parse translated manifest row: {line.strip()}")
            continue
        src = os.path.normpath(os.path.join(i18n_dir, link.group(1)))
        rel = os.path.relpath(src, ROOT).replace(os.sep, "/")
        newer = git("log", "--oneline", f"{sha.group(1)}..HEAD", "--", rel)
        if newer is None:
            fail(name, f"git unavailable or commit {sha.group(1)} not in history for {rel}")
        elif newer:
            fail(name, f"i18n translation of {rel} is STALE ({len(newer.splitlines())} "
                       "commit(s) after the recorded source commit)")


# ---------------------------------------------------------------------------
# 8. Enterprise posture ↔ compliance register (ADR-0015 / #248)
# ---------------------------------------------------------------------------
# The posture must not be prose-only. If AGENTS.md declares the enterprise posture, the
# compliance register (docs/compliance/README.md) must exist; and the register must not exist
# without the declaration. Two directions so neither the doc nor the AGENTS.md clause can drift
# out on its own — the same both-ways discipline the ADR-index and bug-ledger checks use.
_ENTERPRISE_MARKER = "enterprise governance posture"


def check_posture():
    name = "posture"
    agents = read("AGENTS.md") if exists("AGENTS.md") else ""
    declared = _ENTERPRISE_MARKER in agents
    register = exists("docs/compliance/README.md")
    if declared and not register:
        fail(name, "AGENTS.md declares the enterprise governance posture but "
                   "docs/compliance/README.md (the control register) is missing")
    if register and not declared:
        fail(name, "docs/compliance/README.md exists but AGENTS.md does not declare the "
                   "enterprise governance posture — the register has no posture to serve")


CHECKS = [
    check_version_lockstep,
    check_adr_index,
    check_patterns,
    check_spec_map,
    check_milestones,
    check_bugs,
    check_i18n_freshness,
    check_posture,
]


def main():
    for fn in CHECKS:
        try:
            fn()
        except Exception as exc:  # a check crashing is itself a failure
            fail(fn.__name__, f"check crashed: {exc!r}")
    if failures:
        print("Consistency lint: FAIL\n")
        for check, message in failures:
            print(f"  [{check}] {message}")
        print(f"\n{len(failures)} congruence problem(s) found.")
        return 1
    print("Consistency lint: OK — all congruence invariants hold.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
